DROP DATABASE IF EXISTS IRRIGACAO;

CREATE DATABASE IRRIGACAO;

CREATE USER 'irrigacao'@'localhost' IDENTIFIED BY 'ifes2017';
GRANT INSERT, SELECT ON IRRIGACAO.* TO 'irrigacao'@'localhost';

USE IRRIGACAO;

CREATE TABLE UMIDADE
(
	UMID_ID_UMIDADE INT AUTO_INCREMENT,
	UMID_VL_UMIDADE INT NOT NULL,
	UMID_DT_UMIDADE DATETIME NOT NULL,
	PRIMARY KEY (UMID_ID_UMIDADE)
);